name: Deploy-Github-Pages

on:
  workflow_dispatch:

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v4

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public     
